config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  mount Ckeditor::Engine => '/admin/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/tryouts', :to => 'tryouts#index', :as => 'tryouts'

  get '/tryouts/registration', :to => 'tryouts#registration', :as => 'tryouts_registration'
  post '/tryouts/registration', :to => 'tryouts#registration_create', :as => 'tryouts_registration_create'
  get '/tryouts/agegroupchart', :to => 'tryouts#agegroupchart', :as => 'tryouts_agegroupchart'
  get '/tryouts/agelevel', :to => 'tryouts#agelevel', :as => 'tryouts_agelevel'


  get '/portal/:uid', :to => 'player_portals#index', :as => 'player_portal'
  post '/portal/:uid', :to => 'player_portals#events', :as => 'player_portal_events'
  post '/portal/:uid/refund', :to => 'player_portals#events_refund', :as => 'player_portal_events_refund'
  get '/portal/:uid/login', :to => 'player_portals#session_new', :as => 'player_portal_login'
  post '/portal/:uid/login', :to => 'player_portals#session_create', :as => 'player_portal_create'
  get '/portal/:uid/logout', :to => 'player_portals#session_destroy', :as => 'player_portal_logout'
  get '/portal/:uid/clubform', :to => 'player_portals#club_form', :as => 'player_portal_club_form'
  get '/portal/:uid/registration', :to => 'player_portals#registration', :as => 'player_portal_registration'
  post '/portal/:uid/registration', :to => 'player_portals#registration_create', :as => 'player_portal_registration_create'

  get '/news/', :to => 'articles#index', :as => 'articles'
  get '/news/:id', :to => 'articles#show', :as => 'article'

  get '/coaches/', :to => 'coaches#index', :as => 'coaches'
  get '/coaches/:id', :to => 'coaches#show', :as => 'coach'

  get '/teams/', :to => 'teams#index', :as => 'teams'
  get '/teams/:id', :to => 'teams#show', :as => 'team'

  get '/fields/', :to => 'fields#index', :as => 'fields'
  get '/fields/:id', :to => 'fields#show', :as => 'field'

  get '/contact', to: 'contact#index', as: 'contact'
  get '/calendar', to: 'calendar#index', as: 'calendar'

  get '/information', to: 'information#index', as: 'information'
  get '/information/gold', to: 'information#gold', as: 'gold'
  get '/information/silver', to: 'information#silver', as: 'silver'
  get '/information/academy', to: 'information#academy', as: 'academy'
  get '/information/on-equal-footing', to: 'information#scholarship', as: 'scholarship'

  get '/referees', to: 'information#referees', as: 'referees'
  get '/referees/2-man-ref-system', to: redirect('/referees')
  get '/tournaments', to: 'information#tournaments', as: 'tournaments'
  get '/field-setup', to: 'information#field_setup'

  post '/web_part/save', to: 'web_part#update', as: 'update_web_part'
  post '/web_part/translate', to: 'web_part#translate', as: 'translate_content'
  get '/web_part/:locale', to: 'web_part#show', as: 'web_part'
end

app/controllers/tryouts_controller.rb
class TryoutsController < CmsController

  @@mutex = Mutex.new

  def index
    init_web_parts('Tryouts Overview')

    @year = Event::TRYOUT_YEAR
    @tryouts = Event.where(category: Event::categories[:tryout])
  end

  def registration
    @tryout_registration = TryoutRegistration.new
  end

  def registration_create

    @tryout_registration = TryoutRegistration.new(params.required(:tryout_registration)
                                                  .permit(:first, :last, :email, :home_address, :city, :zip, :gender, :birthdate,
                                                          :age, :previous_team, :parent1_first, :parent1_last, :parent1_homePhone, :parent1_businessPhone,
                                                          :parent1_cell, :parent1_email, :parent2_first, :parent2_last, :parent2_homePhone, :parent2_businessPhone,
                                                          :parent2_cell, :parent2_email, :emergency_contact1_name, :emergency_contact1_phone1, :emergency_contact1_phone2,
                                                          :emergency_contact2_name, :emergency_contact2_phone1, :emergency_contact2_phone2,
                                                          :physician_name, :physician_phone1, :physician_phone2, :insurance_name, :insurance_phone,
                                                          :policy_holder, :policy_number, :alergies, :medical_conditions,
                                                          :completed_by, :relationship, :waiver))

    @tryout_registration.age = Event.age(@tryout_registration.birthdate.year) unless @tryout_registration.birthdate.nil?

    if @tryout_registration.save

      # Make phone numbers consistent
      @tryout_registration.parent1_homePhone = format_phone_number(@tryout_registration.parent1_homePhone)
      @tryout_registration.parent1_businessPhone = format_phone_number(@tryout_registration.parent1_businessPhone)
      @tryout_registration.parent1_cell = format_phone_number(@tryout_registration.parent1_cell)
      @tryout_registration.parent2_homePhone = format_phone_number(@tryout_registration.parent2_homePhone)
      @tryout_registration.parent2_businessPhone = format_phone_number(@tryout_registration.parent2_businessPhone)
      @tryout_registration.parent2_cell = format_phone_number(@tryout_registration.parent2_cell)
      @tryout_registration.emergency_contact1_phone1 = format_phone_number(@tryout_registration.emergency_contact1_phone1)
      @tryout_registration.emergency_contact1_phone2 = format_phone_number(@tryout_registration.emergency_contact1_phone2)
      @tryout_registration.emergency_contact2_phone1 = format_phone_number(@tryout_registration.emergency_contact2_phone1)
      @tryout_registration.emergency_contact2_phone2 = format_phone_number(@tryout_registration.emergency_contact2_phone2)
      @tryout_registration.physician_phone1 = format_phone_number(@tryout_registration.physician_phone1)
      @tryout_registration.physician_phone2 = format_phone_number(@tryout_registration.physician_phone2)
      @tryout_registration.insurance_phone = format_phone_number(@tryout_registration.insurance_phone)

      # Save to google spreadsheet - Age Specific Tab
      update_spreadsheet TryoutRegistration.sheet_name, @tryout_registration

      # Tryout info
      @tryout, @age_group = lookup_tryout(Gender.new(@tryout_registration.gender), @tryout_registration.birthdate.year)

      # Send confirmation email
      TryoutMailer.signup_confirmation(@tryout_registration, @tryout).deliver

      render :action => 'confirmation'
    else
      render :registration
    end

  end

  def agegroupchart

    age_group_info = {
        'U8' => ['4x4', '3 x 15', '4', '0'],
        'U9' => ['7x7', '2 x 25', '4', '1'],
        'U10' => ['7x7', '2 x 25', '4', '1'],
        'U11' => ['9x9', '2 x 30', '4', '1'],
        'U12' => ['9x9', '2 x 30', '4', '1'],
        'U13' => ['11x11', '2 x 35', '5', '3'],
        'U14' => ['11x11', '2 x 40', '5', '3'],
        'U15' => ['11x11', '2 x 40', '5', '3'],
        'U16' => ['11x11', '2 x 40', '5', '3'],
        'U17' => ['11x11', '2 x 45', '5', '3'],
        'U19' => ['11x11', '2 x 45', '5', '3'],
    }

    @season = Event::TRYOUT_YEAR
    @chart_info = []

    # Calculate matrix information
    (Event::MIN_AGE..Event::MAX_AGE - 1).each do |age|
      chart_row = []
      chart_row[0] = @season - age
      chart_row[1] = "U#{age == 17 ? age + 2 : age + 1}"

      @chart_info.append chart_row + age_group_info[chart_row[1]]
    end

    render :layout => 'frame'
  end

  def agelevel
    # Determine the age level based on birthdate and gender
    year = params['year'].to_i
    gender = Gender.new(params['gender'].to_i)

    tryout, age = lookup_tryout(gender, year)

    # Minify the HTML so we can make it part of the JSON
    html = render_to_string :partial => 'tryout_info.html', locals: {age: age, tryout: tryout}, format: :html
    minified = HtmlPress.press html

    respond_to do |format|
      format.json { render json: { html: minified, status: tryout != nil }}
    end
  end

  protected

  def lookup_tryout(gender, year)
    age = EventDetail.year_to_age_group(year)

    tryout_results = []
    tryouts = Event.where(category: Event::categories[:tryout])
    tryouts.each do |tryout|
      boys, girls = tryout.by_age_groups

      # filter to the right gender
      gender_tryouts = (gender.name == 'Boys'? boys : girls)

      tryout_results << gender_tryouts[age] unless gender_tryouts[age].nil?
    end

    [tryout_results.flatten!, EventDetail.age_group_to_string(age)]
  end

  def format_phone_number(phone_number)

    if phone_number.blank?
      return phone_number
    end

    # Get the digits
    phone_number.gsub(/[^\d]/, '')
  end

  def get_worksheet(ss, sheet_name)

    age_level_sheet = ss.worksheet_by_title(sheet_name);

    if age_level_sheet.nil?
      # Create the sheet
      age_level_sheet = ss.add_worksheet(sheet_name)
      age_level_sheet.save

      # add the header rows
      ['Bib #',
       'Date Submitted',
       'First',
       'Last',
       'Email',
       'Home Address',
       'City',
       'State',
       'Zip',
       'Gender',
       'Birthdate',
       'Play up',
       'Level',
       'Previous Team',
       'Parent1 First',
       'Parent1 Last',
       'Parent1 Email',
       'Parent1 Home Phone',
       'Parent1 Business Phone',
       'Parent1 Cell',
       'Parent2 First',
       'Parent2 Last',
       'Parent2 Email',
       'Parent2 Home Phone',
       'Parent2 Business Phone',
       'Parent2 Cell',
       'Emergency Contact1',
       'Emergency Contact1 Phone1',
       'Emergency Contact1 Phone2',
       'Emergency Contact2',
       'Emergency Contact2 Phone1',
       'Emergency Contact2 Phone2',
       'Physician',
       'Physician Phone1',
       'Physician Phone2',
       'Insurance Name',
       'Insurance Phone',
       'Policy Holder',
       'Policy Number',
       'Alergies',
       'Medical Conditions',
       'Signor',
       'Relationship',
       'Agreement',
       'User Agent',
       'Selected',
       'Birth Certificate',
       'USClub Form',
       'Amount Paid & Check #'].each_with_index do |cell, index|

        age_level_sheet[1, index + 1] = cell     # 1 Based indexing
      end
      age_level_sheet.save
    end

    age_level_sheet
  end

  def self.authorize
    # Initialize Google Client
    api_client = Google::APIClient.new(application_name: 'Central Marin Soccer Tryouts', application_version: '1.0.0')
    drive = api_client.discovered_api('drive', 'v2')

    # Load Credentials
    key = Google::APIClient::KeyUtils.load_from_pkcs12(Rails.root.join('config', Rails.application.secrets.google_key_file).to_s, Rails.application.secrets.google_key_secret)
    asserter = Google::APIClient::JWTAsserter.new(
        Rails.application.secrets.google_service_account_id,
        'https://www.googleapis.com/auth/drive',
        key
    )

    # Authorize
    api_client.authorization = asserter.authorize(Rails.application.secrets.google_drive_account)
    session = GoogleDrive.login_with_oauth(api_client.authorization.access_token)
  end

  def self.create_path(session, *args)

    folder = session.collection_by_title(args[0])
    folder = session.root_collection.create_subcollection(args[0]) if folder.nil?
    args.shift  # remove the first folder since we've processed it

    args.each do |subfolder|
      new_folder = folder.subcollection_by_title(subfolder)
      new_folder = folder.create_subcollection(subfolder) if new_folder.nil?

      folder = new_folder
    end

    folder
  end

  def self.upload_string(session, data, folder, filename, content_type = 'image/jpeg')
    self.upload(session, folder, filename) do |file|
      if file.nil?
        # upload tmp file and then replace it
        file = session.upload_from_string('tmp', filename, convert: false, content_type: content_type, file_name: filename)
      end
      file.update_from_string(data)
    end

  end

  def self.upload_local_file(session, local_path, folder, filename, content_type)

    self.upload(session, folder, filename) do |file|
      if file.nil?
        session.upload_from_file(local_path, filename, convert: false, content_type: content_type)
      else
        file.update_from_file(local_path)
      end
    end
  end

  def update_spreadsheet(title, registration_info)

    @@mutex.synchronize do

      # make sure we submit everything in English
      I18n.with_locale(:en) do

        session = TryoutsController.authorize

        ss = session.spreadsheet_by_title(title)
        if ss.nil?
          ss = session.create_spreadsheet(title)
        end

        gender = Gender.new(registration_info.gender).to_s
        ws = get_worksheet(ss, "#{gender} U#{registration_info.age}")
        last_row = ws.num_rows + 1

        # Be explicit about order
        ['',
         Time.now,
         registration_info.first,

app/views/tryouts/_tryout_confirmation.html.haml
%div.grid_16
  %h1
    = "#{@tryout_registration.year} #{t('registration.confirmation.heading')}"
  %div
    = t('registration.confirmation.overview').html_safe
%div.grid_16.box
  %h2
    = t('registration.form.player_heading')
  = show_two_column('first', @tryout_registration.first, 'last', @tryout_registration.last)
  = show_two_column('gender', @tryout_registration.gender == 0 ? t('registration.form.gender_boy') : t('registration.form.gender_girl'), 'birthdate', @tryout_registration.birthdate.strftime('%m-%d-%Y'))
  = show_one_column('email', @tryout_registration.email)
  = show_blank_row
  = show_one_column('address', @tryout_registration.home_address)
  = show_two_column('city', @tryout_registration.city, 'zip', @tryout_registration.zip)
  = show_blank_row

  %h2
    = t('registration.form.parent_heading')

  = show_two_column('first', @tryout_registration.parent1_first, 'last', @tryout_registration.parent1_last)
  = show_two_column('business', number_to_phone(@tryout_registration.parent1_businessPhone, area_code: true), 'home', number_to_phone(@tryout_registration.parent1_homePhone, area_code: true))
  = show_two_column('mobile', number_to_phone(@tryout_registration.parent1_cell, area_code: true), 'email', @tryout_registration.parent1_email)
  = show_blank_row


  -# Show the second parent info if any fields were provided
  - if not (@tryout_registration.parent2_first.blank? |
    and @tryout_registration.parent2_last.blank? |
    and @tryout_registration.parent2_cell.blank? |
    and @tryout_registration.parent2_homePhone.blank? |
    and @tryout_registration.parent2_businessPhone.blank? |
    and @tryout_registration.parent2_email.blank?) |
    %h2
      = t('registration.form.parent_heading')
    = show_two_column('first', @tryout_registration.parent2_first, 'last', @tryout_registration.parent2_last)
    = show_two_column('business', number_to_phone(@tryout_registration.parent2_businessPhone, area_code: true), 'home', number_to_phone(@tryout_registration.parent2_homePhone, area_code: true))
    = show_two_column('mobile', number_to_phone(@tryout_registration.parent2_cell, area_code: true), 'email', @tryout_registration.parent2_email)
    = show_blank_row

    %h2
      = t('registration.form.emergency.heading')
    = show_three_columns('emergency.name', @tryout_registration.emergency_contact1_name,
        'emergency.phone', number_to_phone(@tryout_registration.emergency_contact1_phone1, area_code: true),
        'emergency.phone', number_to_phone(@tryout_registration.emergency_contact1_phone2, area_code: true))
    = show_three_columns('emergency.name', @tryout_registration.emergency_contact2_name,
        'emergency.phone', number_to_phone(@tryout_registration.emergency_contact2_phone1, area_code: true),
        'emergency.phone', number_to_phone(@tryout_registration.emergency_contact2_phone2, area_code: true))
    = show_three_columns('physician.name', @tryout_registration.physician_name,
        'physician.phone', number_to_phone(@tryout_registration.physician_phone1, area_code: true),
        'physician.phone', number_to_phone(@tryout_registration.physician_phone2, area_code: true))
    = show_blank_row

    %h2
      = t('registration.form.medical.heading2')
    = show_two_column('insurance.name', @tryout_registration.insurance_name, 'insurance.phone', number_to_phone(@tryout_registration.insurance_phone, area_code: true))
    = show_two_column('insurance.policy_name', @tryout_registration.policy_holder, 'insurance.policy_number', @tryout_registration.policy_number)
    = show_blank_row
    = show_one_column('medical.alergies', @tryout_registration.alergies)
    = show_one_column('medical.conditions', @tryout_registration.medical_conditions)
    = show_blank_row

%div.grid_16.box
  %h2
    = t('registration.confirmation.tryouts.heading')
  %p
    = t('registration.confirmation.tryouts.overview').html_safe
  = render :partial => 'tryouts/tryout_info', :locals => {age: @age_group, tryout: @tryout }

app/views/tryouts/_tryout_info.html.haml
%h2{:class => 'alt'}
  = age
  %ul
    - if tryout.nil?
      = t('registration.tryouts.no_tryouts')
    - else
      - tryout.each do |detail|
        %li
          = "#{l detail.start} - #{(detail.start + detail.length.minutes).strftime('%l:%M %P')} @" unless detail.start.nil?
          - if detail.location.nil?
            =t('registration.tryouts.location_tba')
          - else
            %a{:href => detail.location.map_url}
              = "#{detail.location.name} - #{detail.location.address}"

app/views/tryouts/confirmation.html.haml
= render :partial => 'tryout_confirmation'

%div.grid_16
  =link_to t('registration.confirmation.register_another'), tryouts_registration_path

app/views/tryouts/index.html.haml
%div.grid_16
  %h1
    = "#{@year} #{t('registration.index.heading')}"

-#%div.grid_16.box
-#  %h2 Central Marin & Marin FC Agree to Merge
-#  %p
-#    Central Marin Soccer Community,
-#  %p
-#    We are pleased to announce that effective January 8th, 2017, Central Marin Soccer Club voted unanimously to merge with Marin FC.  This will be a potentially 6 to 12 month process, but members of both clubs’ leadership are committed to work carefully and diligently to map a path to a successful integration of the two clubs’ offerings and operations.  Additionally, our other alliance partners have been consulted and have expressed their support.
-#  %p
-#    The combined club will be the largest club offering competitive soccer teams for boys and girls across all levels in Marin, from US Soccer sanctioned US Development Academy teams (the most elite competitive level) to National Premier League, NorCal Premier (Marin FC "legacy"), Gold, Silver and Bronze-level (Central Marin "legacy") teams.  For those players aspiring to play collegiate soccer, to those seeking advanced play in High School or those just exploring their high-level love of the game, the merged Marin FC promises to achieve an integrated and broad program for the entire Marin community.
-#  %p
-#    Both Clubs have shared or overlapped in many resources and a natural alignment has existed for many years.  While Marin FC’s focus has been on top-tier Academy and National Premier League teams, the infusion of Central Marin’s focus on Premier, Gold, Silver and Bronze level teams creates a complete soccer picture fitting the talent pool and enthusiasm of our young players.
-#  %p
-#    With united soccer philosophies, the merged club can strengthen the competitive soccer offerings for players, parents and coaches.  As a complete competitive spectrum operating seamlessly including our alliance partners, the merged club will be positioned to attract and retain talent across all competitive levels, including the best coaches available in the county.  We truly believe Marin FC will be the premier soccer club in Marin and we want Marin FC to be your Club!
-#  %p
-#    It is our goal to make this as seamless a process for everyone as possible.  We will maintain a similar cost model and continue our strong commitment to financial aid for deserving families.  The combined club will retain the Marin FC name, colors, and logo across all of our teams from U8-U19.
-#  %p
-#    We’re sure you have a number of additional questions, which we tried to anticipate and answer in the attached Q&A Guide.  If you have further questions or concerns, please do not hesitate to contact us at the email address below.
-#  %p
-#    Central Marin Board
-#    %br
-#      board@centralmarinsoccer.com
-#  %p
-#    * Revised February 6th, 2017
-#
-#
-#%div.grid_16.box
-#  %h2
-#    About the Central Marin Soccer Club and Marin FC Merger
-#  %h3
-#    1. What are the reasons for merging Central Marin Soccer Club and Marin FC?  Why is this good for Central Marin families?
-#  %p
-#    By merging, Central Marin and Marin FC are establishing under one organization the opportunity to play at every competitive level, including NorCal Bronze, Silver, Gold (Central Marin "legacy"), Premier, AND the recent US Soccer sanctioned “US Soccer Academy Status” (Marin FC "legacy") for the truly elite players that aspire to play collegiate level soccer. In addition, the Clubs will be able to centralize operations, attract and retain the best playing and coaching talent, more effectively and efficiently utilize training and playing fields and provide a robust experience for players and their families.
-#  %h3
-#    2. How will the interests of Central Marin teams and players be looked after?
-#  %p
-#    Central Marin’s interests will be maintained by:
-#  %ul
-#    %li
-#      continuing Central Marin’s legacy program in the new merged club,
-#    %li
-#      maintaining approximate cost levels,
-#    %li
-#      continuing the existing financial aid program for deserving families, and
-#    %li
-#      retaining Central Marin coaches.
-#  %h3
-#    3. Is Central Marin represented on the new Board?
-#  %p
-#    Yes, Central Marin will retain its current two representatives on the Marin FC Board and additionally between 1 - 3 members of Central’s Marin Board will become at large board members at Marin FC.
-#  %h3
-#    4. What does this mean for my current team?
-#  %p
-#    Teams will form after tryouts, as they have been in the past. Players will move up and down as they have in the past, but the team formation process should remain the same.
-#  %h3
-#    5. What are the dates for tryouts and how will they be handled?
-#  %p
-#    The first tryouts for “legacy” Marin FC teams will take place the weekend of February 25/26 and March 4.  These tryouts will be for Academy and Premier level teams on the boys side and Premier level teams on the girls side. Tryouts for “legacy” Central Marin teams will be held March 5 and March 11. These tryouts will be for NorCal Bronze, Silver and Gold teams for boys and girls. Any players that do not make the Academy or Premier teams are encouraged to tryout for the NorCal Bronze, Silver and Gold Teams.
-#  %h3
-#    Details are available on Marin FC and Central Marin’s websites.
-#  %p
-#    An information session will be held on February 8th at Pickleweed Community Center in San Rafael, hosted by Central Marin and Marin FC, to address any outstanding questions.
-#  %h3
-#    6. What happens to the cadence of training? Will teams now train more or less, play more or less games, go to more or less tournaments?
-#  %p
-#    Teams that are formed under the legacy Central Marin Model (NorCal Gold, Silver and Bronze teams) will operate very similarly as in the past, but the program will be more standardized with a “base program offering". This base program is seasonal and offers spring training, fall league play, state cup and two tournaments during the fall season.
-#  %p
-#    Teams can also decide independently to expand to include Spring League play, more practices in the fall/spring and/or  more tournaments. As has been the case in the past, there will be additional costs for additions to the base program model.
-#  %p
-#    The legacy Marin FC teams (Premier and Academy Status teams) will continue to play year round and practice three times per week and incur higher player costs than the legacy Central Marin teams.
-#  %h3
-#    7. Will costs go up?
-#  %p
-#    Costs are expected to remain approximately the same as in the past based on Central Marin’s current program. As in the past, all additional activities to the Central Marin base program (see definition of Central Marin base program above), such as more practices, Spring League play and additional tournaments, will incur additional costs.
-#  %h3
-#    8. Will there still be financial aid / OEF support?
-#  %p
-#    Yes, Marin FC will continue to provide financial aid to those families in need. This season Central Marin had a very successful financial aid fundraiser with guest speaker Brandi Chastain, World Cup and Olympic soccer champion. We will continue with our community outreach to attract and retain the best soccer players in Marin County and make soccer financially viable for all ability appropriate soccer players from deserving families.
-#  %h3
-#    9. Will the Central Marin coaches be retained?
-#  %p
-#    Central Marin Soccer Club and Marin FC have agreed to retain all current Central Marin coaches that are in good standing with the Club. Marin FC recognizes the importance of our coaches and fully intends to retain them as part of the newly merged Club.
-#  %h3
-#    10. Will the merger make it more difficult for my child to make a comparable team?
-#  %p
-#    While we do expect that over time more boys and girls will try out for our teams than in the past, our experience tells us that at the Gold, Silver, and Bronze levels, parents prefer their children play closer to home on local teams. To the extent that there are more ability-appropriate players for our teams than in the past, we will endeavor to field additional teams to keep our children closer to home and on local teams.
-#  %h3
-#    11. What is Academy Status and what does it mean for our players and their families?
-#  %p
-#    The U.S. Soccer Development Academy is considered the top tier of youth soccer in the United States, and made up of 150 total clubs comprising teams across five age groups: U-12, U-13, U-14, U-15/16, U-17/18. Marin FC currently has Academy Status for boys U12, U13, and U14 age groups and competes with teams such as San Jose Earthquakes, Sacramento Republic, Ballistic United, and De Anza Force.
-#  %p
-#    Having U.S. Academy Status provides our players with the highest level of play for those players that aspire to this level. Academy Status will not detract from all other NorCal levels of play that currently exist, but instead, add another competitive opportunity.
-#  %h3
-#    12. Will families have to commute greater distances to games, to practices?
-#  %p
-#    Travel should be the same or very similar to what it has been in the past.
-#  %h3
-#    13. Are there more changes in the works?
-#  %p
-#    While we do not anticipate additional changes which we have not discussed in this communication, it is possible that other Clubs may seek to become part of Marin FC in the future. Our guide in addressing changes will continue to be to provide the best possible training in developing our players to the best of their abilities.
-#  %h3
-#    14. How will this affect quality and access to practice fields?
-#  %p
-#    The merged club will be better positioned to share existing fields more effectively and efficiently as one club rather than two separate clubs.
-#  %h3
-#    15. How long will it take to fully integrate the operations of the two Clubs?
-#  %p
-#    Both clubs' boards have created a joint working group to methodically, carefully and collaboratively work together to fully integrate operations over the next 6-12 months. This will include bookkeeping, field coordination, player registration, manager training, evaluations, branding, uniforms, websites, etc. Please be patient with us as we work through the details.
-#  %h3
-#    16.  What is the status of the search for a new Director of Coaching?
-#  %p
-#    Josh Kalkstein and Kelly Coffey are Directors of Coaching at Marin FC and will remain in their current positions. We will begin a search for a third DOC to work with Josh and Kelly. The future structure of coaching and player development at Marin FC will likely be expanded after the merger, and determine specific titles and responsibilities for all DOCs.
-#  %p
-#    * Revised February 6th, 2017
%div.grid_16.box
  %h2
    = t('registration.index.online')
  = link_to t('registration.index.online_link'), tryouts_registration_url, :class => 'alt'

- Array(@tryouts).each do |tryout|
  %div.box{class: 'grid_16'}
    %a{name: tryout.category}
    %h2
      = tryout.title
    = tryout.description.html_safe unless tryout.description.blank?
    %p
      - boys, girls = tryout.by_age_ranges
      - if !boys.empty?
        %h3
          = t('team.gender.boys')
        - boys.each do |age, details|
          = render partial: 'tryouts/tryout_info', :locals => {gender: 'team.gender.boys', age: age, tryout: details}

      - if !girls.empty?
        %h3
          = t('team.gender.girls')
        - girls.each do |age, details|
          = render partial: 'tryouts/tryout_info', :locals => {gender: 'team.gender.girls', age: age, tryout: details}


%div.grid_16.box
  = cms_region(@web_parts, 'tryouts.faq1', :div)

  %div.clear
    &nbsp;

  %div.grid_3
    %label{:for => 'gender'}
      = "#{t('registration.form.gender')} *"

  %div.grid_4
    %input{:type => "radio", :name => 'gender', :value => '0', :required => true}
      = " #{t('registration.form.gender_boy')}"
    %input{:type => "radio", :name => 'gender', :value => '1', :required => true}
      = " #{t('registration.form.gender_girl')}"

  %div.grid_3
    %label{:for => 'birthdate_month'}
      = "#{t('registration.form.birthdate')} *"
  %div.grid_4
    %select#birthdate_year{:name => 'birthdate_year', :required => true}
      %option
      - (Time.now.year - 18..Time.now.year-7).each do |year|
        %option
          = year

  %div.clear
    &nbsp;

  %div.grid_15
    %h4#tryouts_date_and_times
    %input{:name => 'age', :type => 'hidden', :value => ''}

  %div.clear
    &nbsp;

  %div.grid_15#age_group_chart
    %a{:href => '#'}
      = t('registration.index.age_group_chart')

  %div.clear
    &nbsp;

  = cms_region(@web_parts, 'tryouts.faq2', :div)
%div.grid_16.box
  %h2
    = t('registration.index.online')
  = link_to t('registration.index.online_link'), tryouts_registration_url, :class => 'alt'

%div{:id => "dialog", :title => "Age Group Chart"}

- content_for :javascript do
  = javascript_include_tag "tryouts"
  %script
    $(document).ready(soccer.tryouts.init_registration('gender', 'birthdate_year'));
    $(document).ready(soccer.tryouts.show_age_group_chart($('#dialog')));