config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  mount Ckeditor::Engine => '/admin/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/tryouts', :to => 'tryouts#index', :as => 'tryouts'

  get '/tryouts/registration', :to => 'tryouts#registration', :as => 'tryouts_registration'
  post '/tryouts/registration', :to => 'tryouts#registration_create', :as => 'tryouts_registration_create'
  get '/tryouts/agegroupchart', :to => 'tryouts#agegroupchart', :as => 'tryouts_agegroupchart'
  get '/tryouts/agelevel', :to => 'tryouts#agelevel', :as => 'tryouts_agelevel'


  get '/portal/:uid', :to => 'player_portals#index', :as => 'player_portal'
  post '/portal/:uid', :to => 'player_portals#events', :as => 'player_portal_events'
  post '/portal/:uid/refund', :to => 'player_portals#events_refund', :as => 'player_portal_events_refund'
  get '/portal/:uid/login', :to => 'player_portals#session_new', :as => 'player_portal_login'
  post '/portal/:uid/login', :to => 'player_portals#session_create', :as => 'player_portal_create'
  get '/portal/:uid/logout', :to => 'player_portals#session_destroy', :as => 'player_portal_logout'
  get '/portal/:uid/clubform', :to => 'player_portals#club_form', :as => 'player_portal_club_form'
  get '/portal/:uid/registration', :to => 'player_portals#registration', :as => 'player_portal_registration'
  post '/portal/:uid/registration', :to => 'player_portals#registration_create', :as => 'player_portal_registration_create'

  get '/news/', :to => 'articles#index', :as => 'articles'
  get '/news/:id', :to => 'articles#show', :as => 'article'

  get '/coaches/', :to => 'coaches#index', :as => 'coaches'
  get '/coaches/:id', :to => 'coaches#show', :as => 'coach'

  get '/teams/', :to => 'teams#index', :as => 'teams'
  get '/teams/:id', :to => 'teams#show', :as => 'team'

  get '/fields/', :to => 'fields#index', :as => 'fields'
  get '/fields/:id', :to => 'fields#show', :as => 'field'

  get '/contact', to: 'contact#index', as: 'contact'
  get '/calendar', to: 'calendar#index', as: 'calendar'

  get '/information', to: 'information#index', as: 'information'
  get '/information/gold', to: 'information#gold', as: 'gold'
  get '/information/silver', to: 'information#silver', as: 'silver'
  get '/information/academy', to: 'information#academy', as: 'academy'
  get '/information/on-equal-footing', to: 'information#scholarship', as: 'scholarship'

  get '/referees', to: 'information#referees', as: 'referees'
  get '/referees/2-man-ref-system', to: redirect('/referees')
  get '/tournaments', to: 'information#tournaments', as: 'tournaments'
  get '/field-setup', to: 'information#field_setup'

  post '/web_part/save', to: 'web_part#update', as: 'update_web_part'
  post '/web_part/translate', to: 'web_part#translate', as: 'translate_content'
  get '/web_part/:locale', to: 'web_part#show', as: 'web_part'
end

app/controllers/home_controller.rb
# class HomeController < InheritedResources::Base
class HomeController < CmsController

    before_filter :set_section_name

  def index
    init_web_parts('Home')

    # Get all articles to display in the carousel in the proper order
    @articles = ArticleCarousel.all.order("carousel_order").map {|ac| ac.article}

    field_status_count = Field.group(:status).count  # Check to see how many fields are open, closed, and call
    @fields_status = {}
    Field.statuses.each_with_index do |status, index|
      @fields_status[status] = field_status_count[index] || 0
    end
  end

  protected

  def set_section_name
    @top_level_section_name = 'menu.home'
  end
end

app/views/home/index.html.erb
<div class="grid_6">
  <h1>Welcome to the Central Marin Soccer Club</h1>
  <p>The Central Marin Competitive Soccer Club (CMCSC) is comprised of Gold, Silver and Bronze Division select soccer teams serving the central Marin communities of San Rafael, Terra Linda (Dixie), Larkspur, San Anselmo, Ross, Greenbrae, Kentfield and Corte Madera. The club is also home to the U9 Developmental Academy.</p>
  
  <hr />

  <h2 class="alt">Program Information</h2>
  <p>Central Marin Soccer Club offers various levels of league and tournament play. The length of season, and program participation costs varies between each level.</p>
  <a class="right" href="/information">Learn More</a>

</div>

<div id="slider-container" class="grid_10 box">
    <div class="ws_images">
	  <img src="/assets/sample_news.png" />
	  <img src="/assets/sample_news.png" />
<!--
        <% @articles.each_with_index do |article, i| %>
            <%= link_to image_tag(article.image_url.to_s, :id=> "img" + i.to_s) + article.title, article %> 
        <% end  %>
    </div>
    <div class="ws_bullets">
        <div>
        <% @articles.each_with_index do |article, i| %>
            <a href="#img<%=i%>"><%= image_tag article.image_url(:thumb).to_s %><%=i + 1%></a>
        <% end %>
        </div>
-->
    </div>
    <div class="ws_bullets">
	  <a href="#"><h2 class="alt">Test1</h2><span>Lorem ipsum .... dasf adsf asdf</span></a>
	  <a href="#"><h2 class="alt">Test2</h2><span>Lorem ipsum .... dasf adsf asdf</span></a>
	</div>
  
</div>

<div class="padV10 clear"></div>

<div class="grid_10">

  <div class="box">
  <h2>Donate</h2>
  <p>Duis lacus purus, tincidunt nec venenatis ac, rhoncus at nunc. Duis euismod sollicitudin adipiscing. Etiam leo mi</p>

  <form class="right" action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="TVEPGNRXXD2YN">
    <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
    <img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
  </form>

  <div class="clear"></div>
  </div>

  <div class="box">
	<h2>Support Our Sponsors</h2>
	<p class="text-center">
	  <img class="pad5" src="/assets/sample_sponsors1.png" />
	  <img class="pad5" src="/assets/sample_sponsors2.png" />
	  <img class="pad5" src="/assets/sample_sponsors3.png" />
	  <img class="pad5" src="/assets/sample_sponsors4.png" />
	</p>
  </div>
</div>

<div id="field_status" class="grid_6 box relative">
  <div class="bg_inlay"></div>
  <div class="relative">
	<h2>Field Status</h2>
	<ol class="block">
      <% @fields_status.each_with_index do |(status, count), index| %>
	  <li <%= "class='odd' unless index % 2 == 0" %>>
		<div class="grid_3"><%= status %></div>
		<div class="grid_2 text-center"><%=  count %></div>
		<div class="clear"></div>
	  </li>
      <% end %>
	</ol>

	<div class="clear"></div>
	<h4 class="alt">For Full status visit the fields page</h4>
	<a href="/fields" class="right">Fields page</a>
	<div class="clear"></div>
  </div>
</div>
<div class="clear"></div>



<% content_for :javascript do %>
    <%= javascript_include_tag 'home' %>
<% end %>

app/views/home/index.html.haml
- content_for :css do
  = stylesheet_link_tag "home"

%div{class: 'grid_6'}
  = cms_region(@web_parts, 'home.overview', :div)
  %a{class: 'right', href: "#{information_path}"}= t('home.program.link')

%div{class: 'grid_10 box'}
  %div.slider-container
    -#%div
      -#%img{src: "/Summer.jpg", height: 420, width: 560 }
      -#%a{href: "/tryouts#Registration_Night"}
      -#  %img{src: "/Registration_Night.jpg", height: 420, width: 560 }
    -@articles.each do |article|
      %div
        %a{href: "#{show_article(article)}"}
          =image_tag article.image, :alt => article.title, height: "#{Article::IMAGE_HEIGHT}", width: "#{Article::IMAGE_WIDTH}", :title => article.title
          =truncate(article.title, length: 75, truncate_string: "...")

-# Spacer
%div{class: 'grid_16'}
  &nbsp;

%div{class: 'grid_10'}
  %div{class: 'box'}
    = cms_region(@web_parts, 'home.donate', :div)
    %a{class: 'right', href: "#{scholarship_path}"}= t('home.donate.link')

    -#%form{class: 'right', action: 'https://www.sandbox.paypal.com/cgi-bin/webscr', method: 'post'}
    -#  %input{type: 'hidden', name: 'cmd', value: '_s-xclick'}
    -#  %input{type: 'hidden', name: 'hosted_button_id', value: 'TVEPGNRXXD2YN'}
    -#  %input{type: 'image', src: 'https://www.sandbox.paypal.com/en_US/i/btn/btn_donateCC_LG.gif', border:'0', name: 'submit', alt: 'PayPal - The safer, easier way to pay online!' }
    -#  %img{alt:'', border:'0', src:'https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif', width:'1', height:'1'}

    %div{class: 'clear'}

  %div{class: 'box'}
    = cms_region(@web_parts, 'home.sponsors', :div)

%div{id: 'field_status', class: 'grid_6 box relative'}
  %div{class: 'bg_inlay'}
  %div{class: 'relative'}
    %h2= t('home.fields.heading')
    %ol{class: 'block'}
      - @fields_status.each_with_index do |(status, count), index|
        %li{class: ('odd' unless index % 2 == 0)}
          %div{class: 'grid_3'}= status
          %div{class: 'grid_2 text-center'}= count
          %div{class: 'clear'}
    %div{class: 'clear'}
    %h4{class: 'alt'}= t('home.fields.body')
    = link_to t('home.fields.link'), fields_path, class: 'right'
    %div{class: 'clear'}
%div{class: 'clear'}

- content_for :javascript do
  = javascript_include_tag 'home'